### ISSUE TITLE
solr4 configuration SEVERE error after installing the amps to war files and running alfresco

### ISSUE THREAD

**Issue by DBlamire** [Open-MBEE/mms-alfresco#68]
The current setup that the server is using.
Centos 6
Tomcat 7.0.78 
Alfresco Community 5.0.d
ActiveMQ 5.14.5
Elasticsearch 5.4.1 
PostgresQL-9.3

Issue after installing the amps to war files and running alfresco

SEVERE: Exception starting filter Office Services Authentication Filter 
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'AosAuthenticationFilter' is defined 
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:575) 
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1111) 
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:276) 
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191) 
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1117) 
        at org.alfresco.repo.web.filter.beans.BeanProxyFilter.init(BeanProxyFilter.java:64) 
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279) 
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260) 
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105) 
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4854) 
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5542) 
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) 
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) 
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) 
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649) 
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081) 
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
        at java.lang.Thread.run(Thread.java:745) 
 
Jun 23, 2017 4:49:06 PM org.apache.catalina.core.StandardContext filterStart 
SEVERE: Exception starting filter Office Services Filter 
java.lang.ClassNotFoundException: org.alfresco.enterprise.repo.officeservices.service.ServiceFilter 
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720) 
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571) 
        at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:506) 
        at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:488) 
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:115) 
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:258) 
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105) 
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4854) 
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5542) 
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) 
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) 
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) 
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649) 
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081) 
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
        at java.lang.Thread.run(Thread.java:745) 
 
Jun 23, 2017 4:49:06 PM org.apache.catalina.core.StandardContext startInternal 
SEVERE: Error filterStart

**Comment by Enquier** [comment]
This is caused by MMS-Repo unnecessarily overwriting the web.xml file in the alfresco.war/WEB-INF. It replaces the file with one that is valid for Enterprise Alfresco 5.0 and contains references to "Alfresco Office Services" the new Microsoft integration which is only available in Community 5.1. I fixed this by going back into the war application log and retrieving the backed up web.xml and reapplying it. You could also choose to go into the web.xml and comment out anything that references alfresco office services or aos

**Comment by DBlamire** [comment]
I went ahead and commented out in ./usr/local/tomcat/webapps/alfresco/WEB-INF/web.xml
but did not see any change. I am concerned that I might not be looking at the right web.xml, as there seems to be a few in there.
Also tried copying the ./usr/local/tomcat/webapps/examples/WEB-INF/web.xml onto ./usr/local/tomcat/webapps/alfresco/WEB-INF/web.xml


find . -name 'web.xml'
./usr/local/tomcat/web.xml
./usr/local/tomcat/webapps/host-manager/WEB-INF/web.xml
./usr/local/tomcat/webapps/ROOT/WEB-INF/web.xml
./usr/local/tomcat/webapps/docs/appdev/sample/web/WEB-INF/web.xml
./usr/local/tomcat/webapps/docs/WEB-INF/web.xml
./usr/local/tomcat/webapps/alfresco/WEB-INF/web.xml
./usr/local/tomcat/webapps/share/WEB-INF/web.xml
./usr/local/tomcat/webapps/solr4/WEB-INF/web.xml
./usr/local/tomcat/webapps/manager/WEB-INF/web.xml
./usr/local/tomcat/webapps/examples/WEB-INF/web.xml
./usr/local/tomcat/conf/web.xml
./usr/apache-activemq-5.14.5/webapps/admin/WEB-INF/web.xml
./usr/apache-activemq-5.14.5/webapps/api/WEB-INF/web.xml
./usr/apache-activemq-5.14.5/webapps-demo/demo/WEB-INF/web.xml
./usr/apache-activemq-5.14.5/examples/conf/web.xml
./home/userdemo/git/EMS-Repo/src/main/amp/web/WEB-INF/web.xml
./home/userdemo/git/mms/mms-ent/repo-amp/target/mms-amp/web/WEB-INF/web.xml
./home/userdemo/git/mms/mms-ent/repo-amp/src/main/amp/web/WEB-INF/web.xml
./home/userdemo/git/mms/mms-ent/share/target/war/work/org.alfresco/share/WEB-INF/web.xml
./home/userdemo/git/mms/mms-ent/share/target/share/WEB-INF/web.xml
./home/userdemo/git/mms/mms-ent/repo/target/war/work/org.alfresco/alfresco/WEB-INF/web.xml
./home/userdemo/git/mms/mms-ent/repo/target/repo/WEB-INF/web.xml
./opt/alfresco-5.0.d/tomcat/webapps/host-manager/WEB-INF/web.xml
./opt/alfresco-5.0.d/tomcat/webapps/alfresco.bak/WEB-INF/web.xml
./opt/alfresco-5.0.d/tomcat/webapps/alfresco/WEB-INF/web.xml
./opt/alfresco-5.0.d/tomcat/webapps/share/WEB-INF/web.xml
./opt/alfresco-5.0.d/tomcat/webapps/solr4/WEB-INF/web.xml
./opt/alfresco-5.0.d/tomcat/webapps/manager/WEB-INF/web.xml
./opt/alfresco-5.0.d/tomcat/conf/web.xml


I might be muddling the waters and need to wipe it all and start over fresh?

Attached my entire catalina.out log, if it provides any clarity.
[catalina_out.docx](https://github.com/Open-MBEE/mms/files/1102749/catalina_out.docx)

**Comment by DBlamire** [comment]
Also here is ./usr/local/tomcat/webapps/alfresco/WEB-INF/web.xml

[web.docx](https://github.com/Open-MBEE/mms/files/1103049/web.docx)

**Comment by DBlamire** [comment]
It worked, Thank You!
